#.travis.yml
language: ruby
rvm:
  - 2.3.3

# branch whitelist
branches:
  only:
    - master

script: bundle exec jekyll build

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer“

notifications:
  email: false
