source 'https://rubygems.org'
gem 'jekyll', '~> 3.0'
gem 'github-pages'
gem 'nokogiri'
gem 'html-proofer'
gem 'jekyll-sitemap'
gem 'jekyll-redirect-from'
gem 'jekyll-paginate'
gem 'jekyll-seo-tag'
gem 'jekyll-github-metadata'